// <auto-generated />
namespace Soulful.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test08 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test08));
        
        string IMigrationMetadata.Id
        {
            get { return "202005280737136_Test08"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
